# -*- encoding: utf-8 -*-
source 'https://rubygems.org'

gem 'cucumber', '2.3.2'
gem 'kitchen-ansible', path: '../'
gem 'kitchen-vagrant', '0.19.0'
gem 'rspec-expectations', '3.4.0'
gem 'test-kitchen', '1.5.0'

