---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 4
  hosts: all

platforms:
  - name: centos-7.1
    driver_config:
      box: bento/centos-7.1
  - name: trusty64
    driver_config:
      box: ubuntu/trusty64
      box_url: https://atlas.hashicorp.com/ubuntu/trusty64
  - name: debian-jessie
    driver_config:
      box: debian/jessie64
      box_url: https://atlas.hashicorp.com/debian/boxes/jessie64

suites:
  - name: default
    provisioner:
      roles_path: './test/integration/default/cucumber/fixtures/roles/ansible-role-myrole'
      playbook: './test/integration/default/cucumber/fixtures/playbooks/uploading-roles-test-playbook.yml'
  - name: from_source
    provisioner:
      require_ansible_repo: false
      require_ansible_source: true
      playbook: './test/integration/from_source/default.yml'